import {
    version
} from '../package.json';

import './style.css';

import * as THREE from 'three';
import {
    OrbitControls,
    GLTFLoader,
    CCDIKSolver,
    CCDIKHelper,
    TransformControls
} from 'three/examples/jsm/Addons.js';
import GUI from 'lil-gui';

import * as MATERIALS from './materials';
import * as FUNCTIONS from './genericFcts';
import * as DRAGGABLE from './draggable.js';

import * as CONFIG from './characterConfig.js';

//global variables
let progressMain, progressSecondary, progressStep;
const progressState = {};
let scene, camera, renderer, controls;
//ray cast bones
let INTERSECTED, raycaster, skeletonHelper, skeletonUIsubMenu;
const bonesInitTransforms = {};
const pointer = new THREE.Vector2();
//useful data sets for UI
const IKSolver = {};
const meshList = {};
const gizmoList = {};
const gizmoHelpers = {};
const bonesGeoList = [];
//filter for extra mesh generated by GLTF conversion for material slots
const regex = new RegExp('\_[0-9]+$');
//animation globals
let activeAction, previousAction, actions, mixer;
const clock = new THREE.Clock();
const api = {};

function init() {
    document.getElementById('version').innerText = 'v' + version

    //meta progress UI generation
    const progressGroup = document.createElement('div');
    progressMain = document.createElement('progress');
    progressSecondary = document.createElement('progress');
    const progressTitle = document.createElement('span');
    progressStep = document.createElement('span');
    const loaderAnim = document.createElement('div');
    loaderAnim.classList.add('loader');

    progressGroup.id = 'progressGroup';
    progressGroup.appendChild(progressTitle);
    progressGroup.appendChild(progressMain);
    progressGroup.appendChild(progressStep);
    progressGroup.appendChild(progressSecondary);
    progressGroup.appendChild(loaderAnim);

    progressTitle.textContent = 'Loading';
    document.getElementsByTagName('body')[0].appendChild(progressGroup);

    //progress data
    Object.assign(progressState, {
        global: 0,
        substep: 0,
        current: '',
        total: 5
    });
    FUNCTIONS.onPropertyChange(progressState, function (p, v) {
        updateProgress(p, v);
    });

    //scene setup
    progressState.global = 0 / progressState.total * 100;
    progressState.substep = 0;
    progressState.current = 'Initialazing scene';
    scene = new THREE.Scene();
    camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    renderer = new THREE.WebGLRenderer({
        canvas: document.querySelector('#bg'),
        antialias: true,
        alpha: true
    });

    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(window.innerWidth, window.innerHeight);

    camera.setViewOffset(window.innerWidth * 3, window.innerHeight * 2, window.innerWidth * 1, window.innerHeight *
        0.05, window.innerWidth, window.innerHeight);
    camera.position.set(0, 1, 5);
    camera.zoom = 2;
    camera.updateProjectionMatrix();

    //UI
    const gridHelper = new THREE.GridHelper(200, 50, 0x2c3e50);
    controls = new OrbitControls(camera, renderer.domElement);

    //lights
    const ambiantLight = new THREE.AmbientLight(0xffffff, 1);
    const pointLight1 = new THREE.PointLight(0xffffff, 0.8);
    const pointLight2 = new THREE.PointLight(0xffffff, 0.8);
    pointLight1.position.set(1, 1, 1);
    pointLight2.position.set(-1, 1, -1);
    scene.add(pointLight1, pointLight2, ambiantLight);

    scene.add(gridHelper);
    progressState.substep = 100;

    Object.assign(api, {
        pose: 'Default',
        BackgroundColor: 0xecf0f1,
        lightIntensity: 1.5,
        grid: true,
        selectedBone: null,
        skeletonHelper: false,
        selectedBoneGizmo: null,
        mode: 'rotate',
        resetBoneFct: function () {
            if (this.selectedBone) {
                switch (this.mode) {
                    case 'rotate':
                        this.selectedBone.setRotationFromEuler(bonesInitTransforms[this.selectedBone.name]
                            .rotation);
                        break;
                    case 'translate':
                        this.selectedBone.position.set(bonesInitTransforms[this.selectedBone.name].position
                            .x, bonesInitTransforms[this.selectedBone.name].position.y,
                            bonesInitTransforms[this.selectedBone.name].position.z);
                        break;
                    case 'scale':
                        this.selectedBone.scale.set(bonesInitTransforms[this.selectedBone.name].scale.x,
                            bonesInitTransforms[this.selectedBone.name].scale.y, bonesInitTransforms[
                                this.selectedBone.name].scale.z);
                        break;
                }
            }
        },
        mirrorPose: false,
        IK: false
    });
    //call update from api static properties changes
    FUNCTIONS.onPropertyChange(api, function (p, v) {
        switch (p) {
            case 'mode':
                this.selectedBoneGizmo.setMode(v);
                reskinGizmo(this.selectedBoneGizmo);
                break;
            case 'skeletonHelper':
                if (v) {
                    reskinGizmo(this.selectedBoneGizmo);
                    for (let i = 0; i < bonesGeoList.length; i++) {
                        scene.add(bonesGeoList[i]);
                    }
                } else {
                    api.selectedBoneGizmo.detach();
                    api.selectedBone = null;
                    skeletonUIsubMenu.name('Show Bones');
                    for (let i = 0; i < bonesGeoList.length; i++) {
                        scene.remove(bonesGeoList[i]);
                    }
                }
                break;
            case 'BackgroundColor':
                scene.background = new THREE.Color(v);
                break;
            case 'grid':
                gridHelper.visible = v;
                break;
            case 'lightIntensity':
                ambiantLight.intensity = v;
                break;
        };
    });

    const srcFile = CONFIG.filePath;
    const loader = new GLTFLoader();
    loader.load(
        srcFile,
        function (gltf) {
            //init meta progress
            progressState.global = 2 / progressState.total * 100;
            progressState.substep = 0;
            progressState.current = 'Unpacking scene';
            let count = 0;
            gltf.scene.traverse(child => {
                count++;
            })
            let progress = 0;

            let skinnedMesh;
            gltf.scene.traverse(function (child) {
                if (child instanceof THREE.Mesh) {
                    //populate meshList
                    if (!regex.test(child.name)) {
                        meshList[child.name] = true;
                    } else {
                        let subName = child.name.replace(regex, '')
                        meshList[subName] = true;
                    }
                    //apply materials
                    Object.keys(CONFIG.matApplication).forEach(m => {
                        if (CONFIG.matApplication[m].includes(child.name)) {
                            if (m == 'diffuseMaterial') {
                                child.material.vertexColors = false;
                                child.material.envMapIntensity = 0;
                            } else {
                                child.material = MATERIALS[m];
                            }
                        }
                    });
                    //store base Skinned mesh
                    if (child.name == CONFIG.skinnedMeshName) skinnedMesh = child;
                } else {
                    if (child instanceof THREE.Bone) {
                        bonesInitTransforms[child.name] = {
                            position: Object.assign({}, child.position),
                            rotation: Object.assign({}, child.rotation),
                            scale: Object.assign({}, child.scale)
                        };
                    }
                }
                progress++;
                progressState.substep = progress / count * 100;
            })

            skeletonHelper = new THREE.SkeletonHelper(gltf.scene);
            generateUIskeleton(skeletonHelper, CONFIG.boneCtrlExclusions);

            setupCustomCtrls(skeletonHelper, skinnedMesh);

            //add scene and generate UI
            scene.add(gltf.scene);
            createGUI(gltf.scene, gltf.animations, skinnedMesh, CONFIG.hiddenMeshes);

            raycaster = new THREE.Raycaster();
            document.addEventListener('mousemove', onPointerMove);

            let gizmoSelectedBone = new TransformControls(camera, renderer.domElement);
            gizmoSelectedBone.setMode('rotate');
            gizmoSelectedBone.space = 'local';
            gizmoSelectedBone.size = 0.3;
            gizmoSelectedBone.addEventListener('mouseDown', () => controls.enabled = false);
            gizmoSelectedBone.addEventListener('mouseUp', () => controls.enabled = true);
            api.selectedBoneGizmo = gizmoSelectedBone;
            renderer.domElement.addEventListener('click', () => {
                if (INTERSECTED) {
                    let bone = skeletonHelper.bones.find(b => b.name == INTERSECTED.name);
                    gizmoSelectedBone.attach(bone);
                    api.selectedBone = bone;
                    scene.add(gizmoSelectedBone.getHelper());
                    skeletonUIsubMenu.name('Show Bones (' + INTERSECTED.name + ')');
                }
            });

            //trigger listener to refresh applied values
            api.skeletonHelper = api.skeletonHelper;
            api.lightIntensity = api.lightIntensity;

            progressState.global = 5 / progressState.total * 100;
            progressState.substep = 100;
            progressState.current = 'Finishing work';

            animate();
        },
        function (xhr) {
            progressState.global = 1 / progressState.total * 100;
            progressState.substep = xhr.loaded / xhr.total * 100;
            progressState.current = 'Retrieving data';
        },
        function (error) {
            alert(error);
        }
    );
};

init();

function createGUI(model, animations, skinnedMesh, hiddenMeshes) {
    progressState.global = 4 / progressState.total * 100;
    progressState.substep = 0;
    progressState.current = 'Making UI';
    let progress = 0;
    let count = 5;
    progressState.substep = ++progress / count * 100;

    const poses = [];

    const gui = new GUI();
    mixer = new THREE.AnimationMixer(model);
    actions = {};

    //Interface general controls
    const sceneFolder = gui.addFolder('Interface');
    sceneFolder.addColor(api, 'BackgroundColor').name('Background color');
    sceneFolder.add(api, 'lightIntensity', 1, 5, 0.1).name('Light intensity');
    sceneFolder.add(api, 'grid').name('3D Grid');
    skeletonUIsubMenu = sceneFolder.add(api, 'skeletonHelper').name('Show Bones');
    sceneFolder.add(api, 'mode').options(['rotate', 'translate', 'scale']).name('Mode');
    sceneFolder.add(api, 'resetBoneFct').name('Reset Bone');
    sceneFolder.add(api, 'mirrorPose').name('Mirror Pose');
    sceneFolder.add(api, 'IK').name('Enable IK');

    //retreive animations
    for (let i = 0; i < animations.length; i++) {
        const clip = animations[i];
        poses.push(animations[i].name);
        const action = mixer.clipAction(clip);
        actions[clip.name] = action;
        if (poses.indexOf(clip.name) >= 0) {
            action.clampWhenFinished = true;
            action.loop = THREE.LoopOnce;
        }
    }

    //mesh list
    const meshFolder = gui.addFolder('Meshes');
    Object.keys(meshList).forEach(e => {
        let toggle = meshFolder.add(meshList, e).name(e);
        hiddenMeshes.forEach(m => {
            if (m == e) {
                toggle.setValue(false);
            }
        })
    });
    progressState.substep = ++progress / count * 100;

    //shape keys
    const morphMesh = skinnedMesh;
    const expressions = Object.keys(morphMesh.morphTargetDictionary);
    const expressionFolder = gui.addFolder('Morph targets');
    for (let i = 0; i < expressions.length; i++) {
        let ctrl = expressionFolder.add(morphMesh.morphTargetInfluences, i, 0, 1, 0.01).name(expressions[i]);

        let subMeshCollection = {};
        model.traverse(function (obj) {
            if (obj instanceof THREE.Mesh) {
                if (obj.morphTargetDictionary != undefined) {
                    let x = obj.morphTargetDictionary[expressions[i]];
                    if (x != undefined) {
                        subMeshCollection[obj.name] = obj;
                    }
                }
            }
        })
        ctrl.onChange((v) => {
            Object.values(subMeshCollection).forEach((e) => {
                e.morphTargetInfluences[e.morphTargetDictionary[expressions[i]]] = v;
            })
        });
    }
    progressState.substep = ++progress / count * 100;

    //gizmos
    const gizmoFolder = gui.addFolder('IK & utils');
    Object.keys(gizmoList).forEach(e => {
        gizmoFolder.add(gizmoList, e).name(e);
    });
    progressState.substep = ++progress / count * 100;


    //poses
    const poseFolder = gui.addFolder('Poses');
    const clipCtrl = poseFolder.add(api, 'pose').options(poses).name('Pose');
    clipCtrl.onChange(function () {
        fadeToAction(api.pose, 0.5);
    });
    poseFolder.open();

    activeAction = actions['Default'];
    activeAction.play();
    progressState.substep = ++progress / count * 100;

    meshFolder.close();
    expressionFolder.close();
    gizmoFolder.close();
    gui.close();

    DRAGGABLE.makeElementTouchDraggable(gui.domElement);
}

function fadeToAction(name, duration) {
    previousAction = activeAction;
    activeAction = actions[name];
    if (previousAction !== activeAction) {
        previousAction.fadeOut(duration);
    }
    activeAction
        .reset()
        .setEffectiveTimeScale(1)
        .setEffectiveWeight(1)
        .fadeIn(duration)
        .play();
}

function reskinGizmo(gizmo) {
    const colors = {
        x: new THREE.Color(0xe74c3c),
        y: new THREE.Color(0xecc71),
        z: new THREE.Color(0x2980b9),
        xyz: new THREE.Color(0xf1c40f)
    }
    switch (gizmo.mode) {
        case 'translate':
            gizmo._gizmo.gizmo.translate.traverse(child => {
                if (child instanceof THREE.Mesh && (child.name == 'X' || child.name == 'Y' || child.name ==
                        'Z')) {
                    child.geometry = new THREE.CylinderGeometry(0.04, 0.04, 1, 12);
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial);
                    switch (child.name) {
                        case 'X':
                            child.geometry.rotateX(0.5 * Math.PI).rotateY(0.5 * Math.PI);
                            newMat.color = colors.x;
                            break;
                        case 'Y':
                            newMat.color = colors.y;
                            break;
                        case 'Z':
                            child.geometry.rotateX(0.5 * Math.PI).rotateZ(0.5 * Math.PI);
                            newMat.color = colors.z;
                            break;
                    }
                    child.material = newMat;
                } else if (child instanceof THREE.Mesh && child.name == 'XYZ') {
                    child.geometry = new THREE.OctahedronGeometry(0.25, 0);
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial)
                    newMat.color = colors.xyz;
                    child.material = newMat;
                }
            });
            break;
        case 'rotate':
            gizmo._gizmo.gizmo.rotate.traverse(child => {
                if (child instanceof THREE.Mesh && (child.name == 'X' || child.name == 'Y' || child.name ==
                        'Z')) {
                    child.geometry = new THREE.TorusGeometry(0.5, 0.05, 12, 32);
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial);
                    switch (child.name) {
                        case 'X':
                            child.geometry.rotateY(0.5 * Math.PI);
                            newMat.color = colors.x;
                            break;
                        case 'Y':
                            child.geometry.rotateX(0.5 * Math.PI);
                            newMat.color = colors.y;
                            break;
                        case 'Z':
                            newMat.color = colors.z;
                            break;
                    }
                    child.material = newMat;
                } else if (child instanceof THREE.Mesh && child.name == 'E') {
                    child.geometry = new THREE.TorusGeometry(0.7, 0.035, 12, 32);
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial)
                    newMat.color = colors.xyz;
                    child.material = newMat;
                }
            })
            break;
        case 'scale':
            gizmo._gizmo.gizmo.scale.traverse(child => {
                if (child instanceof THREE.Mesh) {
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial);
                    let size = 0.15;
                    switch (child.name) {
                        case 'X':
                            child.geometry = new THREE.BoxGeometry(size, size, size);
                            child.geometry.translate(0.5, 0, 0);
                            newMat.color = colors.x;
                            break;
                        case 'Y':
                            child.geometry = new THREE.BoxGeometry(size, size, size);
                            child.geometry.translate(0, 0.5, 0);
                            newMat.color = colors.y;
                            break;
                        case 'Z':
                            child.geometry = new THREE.BoxGeometry(size, size, size);
                            child.geometry.translate(0, 0, 0.5);
                            newMat.color = colors.z;
                            break;
                        case 'XY':
                            newMat.color = colors.z;
                            break;
                        case 'XZ':
                            newMat.color = colors.y;
                            break;
                        case 'YZ':
                            newMat.color = colors.x;
                            break;
                        case 'XYZ':
                            newMat.color = colors.xyz;
                            break;
                    }
                    child.material = newMat;
                }
            });
            break;
    }
    return gizmo;
}

function gizmoSetup(name, space, mode, size, target) {
    let gizmo = new TransformControls(camera, renderer.domElement);
    gizmo.space = space;
    gizmo.size = size;
    gizmo.setMode(mode);
    reskinGizmo(gizmo);
    gizmoList[name] = false;
    let gizmoHelper = gizmo.getHelper();
    gizmoHelpers[name] = gizmoHelper;
    gizmo.addEventListener('mouseDown', () => controls.enabled = false);
    gizmo.addEventListener('mouseUp', () => controls.enabled = true);

    gizmo.attach(target);

    return gizmo;
}

function applyIK(mesh, name, solver) {
    IKSolver[name] = new CCDIKSolver(mesh, solver);
    let IKHelper = new CCDIKHelper(mesh, solver, 0.01);
    gizmoList[name + 'Helper'] = false;
    gizmoHelpers[name + 'Helper'] = IKHelper;
    scene.add(IKHelper);

    return IKHelper;
}

function updateProgress(property, value) {
    switch (property) {
        case 'global':
            progressMain.value = value / 100
            if (value >= 100) {
                window.setTimeout(() => {
                    progressGroup.style.display = 'none';
                }, 1000)
            }
            break;
        case 'substep':
            progressSecondary.value = value / 100;
            break;
        case 'current':
            progressStep.textContent = value;
            break;
    }
}

function onPointerMove(event) {
    pointer.x = (event.clientX / window.innerWidth) * 2 - 1;
    pointer.y = -(event.clientY / window.innerHeight) * 2 + 1;
}

function generateUIskeleton(skl, boneCtrlExclusions) {
    for (let i = 0; i < skl.bones.length; i++) {
        if (!boneCtrlExclusions.some(s => skl.bones[i].name.includes(s))) {
            let boneGeometry = new THREE.OctahedronGeometry(0.025, 3)
            let newMat = new THREE.MeshMatcapMaterial({});
            newMat.copy(MATERIALS.gizmoMaterial);
            let boneMesh = new THREE.Mesh(boneGeometry, newMat);
            let target = new THREE.Vector3();
            skl.bones[i].getWorldPosition(target);
            boneMesh.position.set(target.x, target.y, target.z);
            boneMesh.name = skl.bones[i].name;
            bonesGeoList.push(boneMesh);
            scene.add(boneMesh);
        }
    }
}

function getMirrorBoneName(name) {
    let mirrorName = name;
    let side = name.substr(name.length - 1)
    switch (side) {
        case 'L':
            mirrorName = mirrorName.replace(/.$/, "R");
            break;
        case 'R':
            mirrorName = mirrorName.replace(/.$/, "L");
            break;
        default:
            return 'none'
    }
    return mirrorName;
}

function animate() {
    requestAnimationFrame(animate);

    //update IK
    if (api.IK && IKSolver && api.pose == 'Default') {
        Object.values(IKSolver).forEach(e => {
            e.update();
        })
    }

    //update meshes visibility
    scene.traverse(function (obj) {
        if (obj.isSkinnedMesh) obj.computeBoundingSphere();
        if (obj instanceof THREE.Mesh) {
            let subName = obj.name.replace(regex, '');
            obj.visible = meshList[subName];
        }
    });

    //update skeleton helper UI position
    for (let i = 0; i < bonesGeoList.length; i++) {
        if (api.skeletonHelper) {
            let target = new THREE.Vector3();
            skeletonHelper.bones.find(b => b.name == bonesGeoList[i].name).getWorldPosition(target);
            bonesGeoList[i].position.set(target.x, target.y, target.z);
        }
    }

    //update mirrored bones transformations
    if (api.mirrorPose) {
        if (api.selectedBone && getMirrorBoneName(api.selectedBone.name) != 'none') {
            let mirrorBone = skeletonHelper.bones.find(b => b.name == getMirrorBoneName(api.selectedBone.name));
            switch (api.mode) {
                case 'rotate':
                    let rotation = new THREE.Euler(api.selectedBone.rotation.x, -api.selectedBone.rotation.y, -api
                        .selectedBone.rotation.z, api.selectedBone.rotation.order);
                    mirrorBone.setRotationFromEuler(rotation);
                    break;
                case 'translate':
                    mirrorBone.position.set(-api.selectedBone.position.x, api.selectedBone.position.y, api.selectedBone
                        .position.z);
                    break;
                case 'scale':
                    mirrorBone.scale.set(api.selectedBone.scale.x, api.selectedBone.scale.y, api.selectedBone.scale.z);
                    break;
            }
        };
    }

    //update gizmos visibility
    Object.keys(gizmoHelpers).forEach(e => {
        if (gizmoList[e] == false) {
            scene.remove(gizmoHelpers[e]);
        } else {
            scene.add(gizmoHelpers[e]);
        }
    })

    const dt = clock.getDelta();
    if (mixer) mixer.update(dt);

    //ray cast
    if (raycaster && api.skeletonHelper) {
        raycaster.setFromCamera(pointer, camera);
        const intersects = raycaster.intersectObjects(bonesGeoList, false);
        if (intersects.length > 0) {
            INTERSECTED = intersects[0].object;
            INTERSECTED.material.color = new THREE.Color(0xffff00);
        } else {
            for (let i = 0; i < bonesGeoList.length; i++) {
                bonesGeoList[i].material.color = new THREE.Color(0xffffff);
            }
            INTERSECTED = null;
        }
    }

    //draw new frame
    renderer.render(scene, camera);
}

//non-generic function based on this model skeleton architecture
//might need adjustments for other custom models
//should be de-coupled from character config completely if project is generalized for any character file input
function setupCustomCtrls(sklHelper, sknMesh) {
    progressState.global = 3 / progressState.total * 100;
    progressState.substep = 0;
    progressState.current = 'Setting up controls';
    let progress = 0;
    let count = 4;

    //setup IK settings
    const IKArmL = [{
        target: sklHelper.bones.findIndex(o => o.name == 'ArmIKL'),
        effector: sklHelper.bones.findIndex(o => o.name == 'HandL'),
        links: [{
                index: sklHelper.bones.findIndex(o => o.name == 'ForearmL')
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'ArmL')
            }
        ]
    }];

    const IKArmR = [{
        target: sklHelper.bones.findIndex(o => o.name == 'ArmIKR'),
        effector: sklHelper.bones.findIndex(o => o.name == 'HandR'),
        links: [{
                index: sklHelper.bones.findIndex(o => o.name == 'ForearmR')
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'ArmR')
            }
        ]
    }];

    const IKtail = [{
        target: sklHelper.bones.findIndex(o => o.name == 'TailIK'),
        effector: sklHelper.bones.findIndex(o => o.name == 'Tail05'),
        links: [{
                index: sklHelper.bones.findIndex(o => o.name == 'Tail04'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Tail03'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Tail02'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Tail01'),
            }
        ]
    }];

    const IKEarL = [{
        target: sklHelper.bones.findIndex(o => o.name == 'EarIKL'),
        effector: sklHelper.bones.findIndex(o => o.name == 'Ear05L'),
        links: [{
                index: sklHelper.bones.findIndex(o => o.name == 'Ear04L'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Ear03L'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Ear02L'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Ear01L'),
            }
        ]
    }];

    const IKEarR = [{
        target: sklHelper.bones.findIndex(o => o.name == 'EarIKR'),
        effector: sklHelper.bones.findIndex(o => o.name == 'Ear05R'),
        links: [{
                index: sklHelper.bones.findIndex(o => o.name == 'Ear04R'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Ear03R'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Ear02R'),
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'Ear01R'),
            }
        ]
    }];

    const IKLegL = [{
        target: sklHelper.bones.findIndex(o => o.name == 'LegIKL'),
        effector: sklHelper.bones.findIndex(o => o.name == 'ToesL'),
        links: [{
                index: sklHelper.bones.findIndex(o => o.name == 'FootL')
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'LowerLegL')
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'UpperLegL')
            }
        ]
    }];

    const IKLegR = [{
        target: sklHelper.bones.findIndex(o => o.name == 'LegIKR'),
        effector: sklHelper.bones.findIndex(o => o.name == 'ToesR'),
        links: [{
                index: sklHelper.bones.findIndex(o => o.name == 'FootR')
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'LowerLegR')
            },
            {
                index: sklHelper.bones.findIndex(o => o.name == 'UpperLegR')
            }
        ]
    }];
    progressState.substep = ++progress / count * 100;

    //setup Gizmo ctrls
    //gizmoSetup('ArmLCtrl', 'world', 'translate', 0.4, sklHelper.bones.find(b => b.name == 'ArmIKL'));
    //gizmoSetup('ArmRCtrl', 'world', 'translate', 0.4, sklHelper.bones.find(b => b.name == 'ArmIKR'));

    let jawCtrl = gizmoSetup('JawCtrl', 'local', 'rotate', 0.3, sklHelper.bones.find(b => b.name == 'Jaw'));
    jawCtrl.showY = false;
    jawCtrl.showZ = false;

    gizmoSetup('TailCtrl', 'world', 'translate', 0.4, sklHelper.bones.find(b => b.name == 'TailIK'));
    gizmoSetup('EarLCtrl', 'world', 'translate', 0.3, sklHelper.bones.find(b => b.name == 'EarIKL'));
    gizmoSetup('EarRCtrl', 'world', 'translate', 0.3, sklHelper.bones.find(b => b.name == 'EarIKR'));
    //gizmoSetup('LegLIK', 'global', 'translate', 0.3, sklHelper.bones.find(b => b.name == 'LegIKL'));
    //gizmoSetup('LegLIR', 'global', 'translate', 0.3, sklHelper.bones.find(b => b.name == 'LegIKR'));
    gizmoSetup('HipsCtrl', 'global', 'translate', 0.4, sklHelper.bones.find(b => b.name == 'Hips'));
    progressState.substep = ++progress / count * 100;

    Object.values(gizmoHelpers).forEach(e => {
        scene.add(e);
    });
    progressState.substep = ++progress / count * 100;

    //apply IK ctrls
    //applyIK(sknMesh, 'armL', IKArmL);
    //applyIK(sknMesh, 'armR', IKArmR);
    applyIK(sknMesh, 'tail', IKtail);
    applyIK(sknMesh, 'earL', IKEarL);
    applyIK(sknMesh, 'earR', IKEarR);
    //applyIK(sknMesh, 'legL', IKLegL);
    //applyIK(sknMesh, 'legR', IKLegR);
    progressState.substep = ++progress / count * 100;
};