/*
* --== Coding Style rules ==--
* ALLCAPS names are related to file and lib imports
* Object starting with a maj are objects/protypes of nature (rule exception: if they are relevant abreviations i.e. IKSolvers)
* global variables must me constants if applicable and are always declared in header right after the imports
* single characters and single words are quoted with '' and longer strings that can contain spaces with ""
* index.html automatically calls main() on load as it is the main app thread and it must pilot everthing else
* every function and variables must be ignorant, file specific variables must be retrieved from CONFIG
* any generic JS function must be implemented within FUNCTIONS
* any material setup must be done within MATERIALS
* any complex operation used more than once must be implemented in a dedicated function
*/

import { version } from '../package.json';
import './style.css';

import * as THREE from 'three/webgpu';
import {
    OrbitControls,
    GLTFLoader,
    CCDIKSolver,
    CCDIKHelper,
    TransformControls,
    KTX2Loader,
    DRACOLoader
} from 'three/examples/jsm/Addons.js';
import Stats from 'three/addons/libs/stats.module.js';
import GUI from 'lil-gui';

import * as MATERIALS from './materials';
import * as FUNCTIONS from './genericFcts';
import * as DRAGGABLE from './draggable.js';
import * as DQS from './dualQuaternionSkinning.tsl.js';

import { color, mix, mx_fractal_noise_float, pass, positionView } from 'three/tsl';
import { MeshoptDecoder } from 'three/examples/jsm/libs/meshopt_decoder.module.js';

//global variables
let CONFIG;
const progressState = {};
//scene globals
const scene = new THREE.Scene();
let camera, renderer, controls, postProcessing;
//ray cast
let intersected;
const raycaster = new THREE.Raycaster();
const pointer = new THREE.Vector2();
//useful data sets
const IKSolvers = {};
const meshList = {};
const gizmoList = {};
const gizmoHelpers = {};
const bonesGeoList = [];
const bonesInitTransforms = {};
//filter for extra mesh generated by GLTF conversion for material slots
const regex = new RegExp('\_[0-9]+$');
//animation globals
let activeAction, previousAction, actions, mixer;
const clock = new THREE.Timer();
const api = {}; //interface API for UI

window.main = main;
async function main() {
    await FUNCTIONS.loadJSON('/characterConfig.json').then((JSONdata) => {
        CONFIG = JSONdata;
        Object.freeze(CONFIG);
    });
    await init();
    await load();
    renderer.setAnimationLoop(animate);
}

async function init() {
    document.getElementById('version').innerText = 'v' + version;

    //meta progress UI
    const progressGroup = document.createElement('div');
    const progressMain = document.createElement('progress');
    const progressSecondary = document.createElement('progress');
    const progressTitle = document.createElement('span');
    const progressStep = document.createElement('span');
    const loaderAnim = document.createElement('div');
    loaderAnim.classList.add('loader');
    progressGroup.id = 'progressGroup';
    progressGroup.appendChild(progressTitle);
    progressGroup.appendChild(progressMain);
    progressGroup.appendChild(progressStep);
    progressGroup.appendChild(progressSecondary);
    progressGroup.appendChild(loaderAnim);
    progressTitle.textContent = "Loading";
    document.getElementsByTagName('body')[0].appendChild(progressGroup);

    Object.assign(progressState, {
        global: 0,
        substep: 0,
        current: "<Current Step>",
        total: 5
    });

    //progress data listener
    FUNCTIONS.onPropertyChange(progressState, (p, v) => {
        switch (p) {
            case 'global':
                progressMain.value = v / 100
                if (v >= 100) {
                    window.setTimeout(() => {
                        progressGroup.style.display = 'none';
                    }, 1000)
                }
                break;
            case 'substep':
                progressSecondary.value = v / 100;
                break;
            case 'current':
                progressStep.textContent = v;
                break;
        }
    });

    const video = document.getElementById('video');

    //scene setup
    progressState.global = 0 / progressState.total * 100;
    progressState.substep = 0;
    progressState.current = "Initialazing scene";
    camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    renderer = new THREE.WebGPURenderer({
        canvas: document.querySelector('#bg'),
        antialias: true,
        alpha: true,
        powerPreference: 'high-performance'
    });

    renderer.setPixelRatio(window.devicePixelRatio);
    renderer.setSize(window.innerWidth, window.innerHeight);

    camera.setViewOffset(window.innerWidth * 3, window.innerHeight * 2, window.innerWidth * 1, window.innerHeight * 0.05, window.innerWidth, window.innerHeight);
    camera.position.set(0, 1, 5);
    camera.zoom = 2;
    camera.updateProjectionMatrix();

    window.addEventListener('resize', () => {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.setViewOffset(window.innerWidth * 3, window.innerHeight * 2, window.innerWidth * 1, window.innerHeight * 0.05, window.innerWidth, window.innerHeight);
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
    });

    //post processing
    postProcessing = new THREE.PostProcessing(renderer);
    const scenePass = pass( scene, camera );
    const scenePassTM = scenePass.toneMapping(THREE.ACESFilmicToneMapping);
    postProcessing.outputNode = scenePassTM;

    //UI
    const gridHelper = new THREE.GridHelper(200, 50, 0x2c3e50);
    scene.add(gridHelper);
    controls = new OrbitControls(camera, renderer.domElement);

    //lights
    const ambiantLight = new THREE.AmbientLight(0xffffff, 1);
    const pointLight1 = new THREE.PointLight(0xffffff, 1);
    const pointLight2 = new THREE.PointLight(0xffffff, 1);
    pointLight1.position.set(1, 1, 1);
    pointLight2.position.set(-1, 1, -1);
    scene.add(pointLight1, pointLight2, ambiantLight);

    progressState.substep = 100;

    //api interface
    Object.assign(api, {
        pose: CONFIG.defaultPose,
        backgroundColor: 0x76ddfc,
        lightIntensity: 1.5,
        grid: false,
        selectedBone: null,
        skeletonHelperDisplay: false,
        skeletonHelper: null,
        selectedBoneGizmo: null,
        mode: 'rotate',
        resetBoneFct: () => {
            if (api.selectedBone) {
                switch (api.mode) {
                    case 'rotate':
                        api.selectedBone.setRotationFromEuler(bonesInitTransforms[api.selectedBone.name].rotation);
                        break;
                    case 'translate':
                        api.selectedBone.position.set(
                            bonesInitTransforms[api.selectedBone.name].position.x,
                            bonesInitTransforms[api.selectedBone.name].position.y,
                            bonesInitTransforms[api.selectedBone.name].position.z
                        );
                        break;
                    case 'scale':
                        api.selectedBone.scale.set(
                            bonesInitTransforms[api.selectedBone.name].scale.x,
                            bonesInitTransforms[api.selectedBone.name].scale.y,
                            bonesInitTransforms[api.selectedBone.name].scale.z
                        );
                        break;
                }
            }
        },
        mirrorPose: false,
        IK: false,
        wireframe: false,
        backgroundImage: false,
        stats: new Stats(),
        statsVisible: false,
        gui: null,
        sklUImenu: null,
        breathing: true,
        breatheCtrl: null,
        blinkCtrls: []
    });
    //api listeners
    FUNCTIONS.onPropertyChange(api, (p, v) => {
        switch (p) {
            case 'mode':
                api.selectedBoneGizmo.setMode(v);
                break;
            case 'skeletonHelperDisplay':
                if (v) {
                    for (let i = 0; i < bonesGeoList.length; i++) {
                        scene.add(bonesGeoList[i]);
                    }
                } else {
                    api.selectedBoneGizmo.detach();
                    api.selectedBone = null;
                    api.sklUImenu.name('Show Bones');
                    api.gui.domElement.childNodes[1].innerText = 'Controls';
                    for (let i = 0; i < bonesGeoList.length; i++) {
                        scene.remove(bonesGeoList[i]);
                    }
                }
                break;
            case 'backgroundColor':
                if (!api.backgroundImage) scene.backgroundNode = mix(color(v), color(v).mul(2), mx_fractal_noise_float(positionView.mul(5)).mul(0.5));
                break;
            case 'grid':
                gridHelper.visible = v;
                break;
            case 'lightIntensity':
                ambiantLight.intensity = v;
                break;
            case 'backgroundImage':
                if(v) {
                    scene.backgroundNode = null;
                    if ( navigator.mediaDevices && navigator.mediaDevices.getUserMedia ) {
                        const constraints = { video: { facingMode: 'environment' } };
                        navigator.mediaDevices.getUserMedia( constraints ).then( function ( stream ) {
                            video.srcObject = stream;
                            video.play();
                            video.style.display = 'block';
                        } ).catch( function ( error ) {
                            console.error( "Unable to access the camera/webcam.", error );
                        } );
                    } else {
                        console.error( "MediaDevices interface not available." );
                    }
                } else {
                    video.pause();
                    video.style.display = 'none';
                    scene.backgroundNode = mix(color(api.backgroundColor), color(api.backgroundColor).mul(2), mx_fractal_noise_float(positionView.mul(5)).mul(0.5));
                }
                break;
            case 'statsVisible':
                if(v) {
                    api.stats.dom.childNodes.forEach((c) => {c.style.display = 'block'});
                } else {
                    api.stats.dom.childNodes.forEach((c) => {c.style.display = 'none'});
                }
                break;
            case 'breathing':
                if (!v) {
                    if (api.breatheCtrl) {
                        api.breatheCtrl.enable();
                        api.breatheCtrl.setValue(0);
                    }
                    if (api.blinkCtrls.length > 0) {Object.values(api.blinkCtrls).forEach( e => {
                        e.enable();
                        e.setValue(0);
                    });}
                } else {
                    if (api.breatheCtrl) api.breatheCtrl.disable();
                    if (api.blinkCtrls.length > 0) Object.values(api.blinkCtrls).forEach( e => e.disable());
                }
                break;
        };
    });

    //tracks pointer coords to update 'intersected' with any bone UI intersecting with pointer coords
    document.addEventListener('mousemove', (e) => FUNCTIONS.trackPointer(e, pointer));

    await renderer.init();
};

async function load() {  
    const srcFile = CONFIG.filePath;
    const loader = new GLTFLoader();

    /* decoders for compressed assets, used automatically if matching compression is detected in the file
    * compression methods don't seem to be beneficial on low end devices, additional runtime cost is too high compared to the vram gains
    * on high end devices loading is improved and performance cost on runtime is worth it
    */
    const ktx2Loader = new KTX2Loader();
    ktx2Loader.setTranscoderPath('/loaders/basis/');
    ktx2Loader.detectSupport(renderer);
    const dracoLoader = new DRACOLoader();
    dracoLoader.setDecoderConfig({type: 'js'});
    dracoLoader.setDecoderPath('/loaders/draco/');
    loader.setDRACOLoader(dracoLoader);
    loader.setKTX2Loader(ktx2Loader);
    loader.setMeshoptDecoder(MeshoptDecoder);
    
    //init meta progress values
    progressState.global = 1 / progressState.total * 100;
    progressState.substep = 0;
    progressState.current = "Unpacking scene";

    await loader.loadAsync(
        srcFile,
        (data) => {
            progressState.substep = data.loaded / data.total * 100;
        }
    ).then(
        (data) => {
            //init meta progress values
            progressState.global = 2 / progressState.total * 100;
            progressState.substep = 0;
            progressState.current = "Initializing scene";
            let count = 0;
            data.scene.traverse(() => { count++; });
            let progress = 0;

            let skinnedMeshReference;

            data.scene.traverse(function (child) {
                if (child instanceof THREE.Mesh) {
                    //populate meshList
                    if (!regex.test(child.name)) {
                        meshList[child.name] = true;
                    } else {
                        let subName = child.name.replace(regex, '')
                        meshList[subName] = true;
                    }
                    //apply materials
                    Object.keys(CONFIG.matApplication).forEach(m => {
                        if (CONFIG.matApplication[m].includes(child.name)) {
                            if (m == 'diffuseMaterial') {
                                child.material.vertexColors = false;
                                child.material = MATERIALS.convertMaterialToNodes(child.material);
                            } else {
                                child.material = MATERIALS[m];
                            }
                        }
                    });
                    if (!skinnedMeshReference && child.skeleton) skinnedMeshReference = child;
                    if (CONFIG.skinnedMeshNames.includes(child.name)) {
                        child.material = MATERIALS.convertMaterialToNodes(child.material);
                        DQS.enableDQS(child, false);
                    };
                    child.frustumCulled = true;
                } else {
                    if (child instanceof THREE.Bone) {
                        bonesInitTransforms[child.name] = {
                            position: Object.assign({}, child.position),
                            rotation: Object.assign({}, child.rotation),
                            scale: Object.assign({}, child.scale)
                        };
                    }
                }
                progress++;
                progressState.substep = progress / count * 100;
            });

            api.skeletonHelper = new THREE.SkeletonHelper(data.scene);
            generateUIskeleton(api.skeletonHelper, CONFIG.boneCtrlExclusions);
            setupCustomCtrls(api.skeletonHelper, skinnedMeshReference);
            createGUI(data.scene, data.animations, CONFIG.hiddenMeshes);

            scene.add(data.scene);

            progressState.global = 5 / progressState.total * 100;
            progressState.substep = 100;
            progressState.current = "Finishing work";
        },
        (error) => {
            console.error(error);
        }
    );
}

let f = 0;
function animate() {
    if (f < 10) f++; //need to wait a few frames to assert renderer and if fallback is in place or not
    else document.getElementById('renderer').innerText = renderer.backend.constructor.name.split('Backend')[0];

    //update IK
    if (api.IK && IKSolvers && api.pose == 'Default') {
        Object.values(IKSolvers).forEach(e => {
            e.update();
        })
    }

    //update meshes visibility
    scene.traverse(function (obj) {
        if (obj.isSkinnedMesh) obj.computeBoundingSphere();
        if (obj instanceof THREE.Mesh) {
            let subName = obj.name.replace(regex, '');
            obj.visible = meshList[subName];
            if(meshList[subName]) obj.material.wireframe = api.wireframe;
        }
    });

    //update skeleton helper UI position
    for (let i = 0; i < bonesGeoList.length; i++) {
        if (api.skeletonHelperDisplay) {
            let target = new THREE.Vector3();
            api.skeletonHelper.bones.find(b => b.name == bonesGeoList[i].name).getWorldPosition(target);
            bonesGeoList[i].position.set(target.x, target.y, target.z);

            let scale = new THREE.Vector3().subVectors(bonesGeoList[i].position, camera.position).length() * 0.2;
            bonesGeoList[i].scale.set(scale, scale, scale)
        }
    }

    //update mirrored bones transformations
    if (api.mirrorPose) {
        if (api.selectedBone && getMirrorBoneName(api.selectedBone.name) != 'none') {
            let mirrorBone = api.skeletonHelper.bones.find(b => b.name == getMirrorBoneName(api.selectedBone.name));
            switch (api.mode) {
                case 'rotate':
                    let rotation = new THREE.Euler(api.selectedBone.rotation.x, -api.selectedBone.rotation.y, -api
                        .selectedBone.rotation.z, api.selectedBone.rotation.order);
                    mirrorBone.setRotationFromEuler(rotation);
                    break;
                case 'translate':
                    mirrorBone.position.set(-api.selectedBone.position.x, api.selectedBone.position.y, api.selectedBone
                        .position.z);
                    break;
                case 'scale':
                    mirrorBone.scale.set(api.selectedBone.scale.x, api.selectedBone.scale.y, api.selectedBone.scale.z);
                    break;
            }
        };
    }

    //update gizmos visibility
    Object.keys(gizmoHelpers).forEach(e => {
        gizmoList[e] = api.IK; //IK button toggles them all
        if (gizmoList[e] == false) {
            scene.remove(gizmoHelpers[e]);
        } else {
            scene.add(gizmoHelpers[e]);
        }
    })

    if (mixer) mixer.update(clock.getDelta());

    //manual morph target animation adjustments if specified
    if (CONFIG.poseExtraSettings[api.pose]) {
        if (CONFIG.poseExtraSettings[api.pose].morphs) {
            api.gui.children.forEach(e => {
                if (e._title == "Morph targets") { e.children.forEach(g => {
                    if (g._title == 'Body') { g.children.forEach(c => {
                        Object.keys(CONFIG.poseExtraSettings[api.pose].morphs).forEach(t => {
                            if (c._name == t) c.setValue(CONFIG.poseExtraSettings[api.pose].morphs[t]);
                        });
                    })}
                })}
            });
        }
    }

    //'Alive' loop -- based on timeStamp rather than clock.delta because it's independant of animation time scaling and progress
    if (api.breathing) {
        if (api.breatheCtrl) {
            let overriden = false;
            if (CONFIG.poseExtraSettings[api.pose]) if (CONFIG.poseExtraSettings[api.pose].dynamicMorphsOverride) if(Object.values(CONFIG.poseExtraSettings[api.pose].dynamicMorphsOverride).includes(CONFIG.breatheKey)) overriden = true;
            if (!overriden) api.breatheCtrl.setValue(Math.sin((performance.now()*0.0025))*0.35+0.35);
        }
        if (api.blinkCtrls.length > 0) {
            let overriden = false;
            if (CONFIG.poseExtraSettings[api.pose]) if (CONFIG.poseExtraSettings[api.pose].dynamicMorphsOverride) if(Object.values(CONFIG.poseExtraSettings[api.pose].dynamicMorphsOverride).includes(CONFIG.blinkKeys)) overriden = true;
            if (!overriden) {
                let blinkValue = Math.sin((performance.now()*0.0015))*25-24;            
                if (blinkValue >= 0) Object.values(api.blinkCtrls).forEach(e => e.setValue(blinkValue));
                else Object.values(api.blinkCtrls).forEach(e => e.setValue(0));
            }
        }
    }

    DQS.updateDQS();

    //ray cast
    if (raycaster && api.skeletonHelperDisplay) {
        raycaster.setFromCamera(pointer, camera);
        const intersects = raycaster.intersectObjects(bonesGeoList, false);
        if (intersects.length > 0) {
            intersected = intersects[0].object;
            intersected.material.color = new THREE.Color(0xffff00);
        } else {
            for (let i = 0; i < bonesGeoList.length; i++) {
                bonesGeoList[i].material.color = new THREE.Color(0xffffff);
            }
            intersected = null;
        }
    }

    //draw new frame
    postProcessing.renderAsync();

    clock.update();
    api.stats.update();
}

function createGUI(scene, animations, hiddenMeshes) {
    //init meta progress values
    progressState.global = 4 / progressState.total * 100;
    progressState.substep = 0;
    progressState.current = "Making UI";
    let progress = 0;
    let count = 4;
    progressState.substep = ++progress / count * 100;

    //init GUI
    api.gui = new GUI();
    
    const poses = [];
    actions = {};
    mixer = new THREE.AnimationMixer(scene);

    //Interface general controls
    const sceneFolder = api.gui.addFolder("Interface");
    sceneFolder.addColor(api, 'backgroundColor').name("Background color");
    sceneFolder.add(api, 'backgroundImage').name("Camera background");
    sceneFolder.add(api, 'lightIntensity', 1, 5, 0.1).name("Light intensity");
    sceneFolder.add(api, 'grid').name("3D Grid");
    sceneFolder.add(api, 'wireframe').name("Wireframe");
    sceneFolder.add(api, 'statsVisible').name("Show App Stats");
    
    //setup skeleton UI gizmo
    let gizmoSlct = new TransformControls(camera, renderer.domElement);
    gizmoSlct.setMode('translate');
    gizmoSlct = reskinGizmo(gizmoSlct);
    gizmoSlct.setMode('scale');
    gizmoSlct = reskinGizmo(gizmoSlct);
    gizmoSlct.setMode('rotate');
    gizmoSlct = reskinGizmo(gizmoSlct);

    gizmoSlct.space = 'local';
    gizmoSlct.size = 0.3;
    gizmoSlct.addEventListener('mouseDown', () => controls.enabled = false);
    gizmoSlct.addEventListener('mouseUp', () => controls.enabled = true);
    
    api.selectedBoneGizmo = gizmoSlct;
    
    renderer.domElement.addEventListener('click', () => {
        if (intersected) {
            let bone = api.skeletonHelper.bones.find(b => b.name == intersected.name);
            api.selectedBoneGizmo.attach(bone);
            api.selectedBone = bone;
            scene.add(api.selectedBoneGizmo.getHelper());
            api.sklUImenu.name("Show Bones (" + intersected.name + ")");
            if (api.gui.domElement.classList.contains('closed')) api.gui.domElement.childNodes[1].innerText = "Controls (" + intersected.name + ")";
        }
    });

    const scenePoseFolder = api.gui.addFolder("Pose utils");
    api.sklUImenu = scenePoseFolder.add(api, 'skeletonHelperDisplay').name("Show Bones");
    scenePoseFolder.add(api, 'mode').options(['rotate', 'translate', 'scale']).name("Mode");
    scenePoseFolder.add(api, 'resetBoneFct').name("Reset Bone");
    scenePoseFolder.add(api, 'mirrorPose').name("Mirror Pose");
    scenePoseFolder.add(api, 'IK').name("IK Controls (Default pose only)");

    progressState.substep = ++progress / count * 100;

    //mesh list
    const meshFolder = api.gui.addFolder("Meshes");
    Object.keys(meshList).forEach(e => {
        let toggle = meshFolder.add(meshList, e).name(e);
        hiddenMeshes.forEach(m => {
            if (m == e) {
                toggle.setValue(false);
            }
        })
    });

    //shape keys
    const expressionFolder = api.gui.addFolder("Morph targets");
    let found = false;
    scene.traverse(m => {
        if (m instanceof THREE.Mesh) {
            if (CONFIG.morphMeshList.includes(m.name)) {
                let morphMeshFolder = expressionFolder.addFolder(m.name.split('_')[0]);
                registerMorphMesh(scene, m, morphMeshFolder);
                found = true;
            }
        }
    });
    if (!found) console.warn("No matching mesh for morphTargets found. Looking for:", CONFIG.morphMeshList);

    //add search bar to morph target lists
    for (let i = 0; i < expressionFolder.domElement.childNodes[1].childNodes.length; i++) {
        let searchBar = addSearch(expressionFolder.domElement.childNodes[1].childNodes[i].childNodes[1]);
        if (searchBar) {
            let div = document.createElement('div');
            div.classList.add('controller');
            div.appendChild(searchBar);
            expressionFolder.domElement.childNodes[1].childNodes[i].childNodes[1].prepend(div);
        }
    }
    progressState.substep = ++progress / count * 100;

    //retreive poses (or animations)
    for (let i = 0; i < animations.length; i++) {
        const clip = animations[i];
        poses.push(animations[i].name);
        const action = mixer.clipAction(clip);
        actions[clip.name] = action;
        if (poses.indexOf(clip.name) >= 0) {
            action.clampWhenFinished = true;
        }
    }

    //poses (or animations)
    const poseFolder = api.gui.addFolder("Poses & animations");
    const clipCtrl = poseFolder.add(api, 'pose').options(poses).name("Active");
    clipCtrl.onChange(function () {
        fadeToAction(api.pose, 0.5);
        //automatic mesh toggling animations if specified
        if (CONFIG.poseExtraSettings[api.pose]) {
            if (CONFIG.poseExtraSettings[api.pose].meshes) {
                api.gui.children.forEach(e => {if (e._title == "Meshes") {e.children.forEach(m => {
                    if (CONFIG.poseExtraSettings[api.pose].meshes[m._name] != undefined) m.setValue(CONFIG.poseExtraSettings[api.pose].meshes[m._name]);
                })}});
            }
        }
    });
    poseFolder.add(api, 'breathing').name('Alive');
    poseFolder.open();

    CONFIG.poseExtraSettings.morphClearDefault.forEach((e) => {
        expressionFolder.children.forEach((c) => {
            c.children.forEach((t) => {
                if (t._name == e) t.setValue(0);
            });
        });
    });
    activeAction = actions[CONFIG.defaultPose];
    if (activeAction) activeAction.play();
    else console.warn("Default pose '"+ CONFIG.defaultPose + "' was not found.");
    progressState.substep = ++progress / count * 100;

    scenePoseFolder.close();
    meshFolder.close();
    expressionFolder.close();
    api.gui.close();

    DRAGGABLE.makeElementTouchDraggable(api.gui.domElement);

    //external stats UI
    document.body.appendChild(api.stats.dom);
    api.stats.dom.inert = true;
    api.stats.dom.style.margin = "10% 0.5em";

    //trigger listeners to initialize & sync api values
    Object.keys(api).forEach((param) => {
        api[param] = api[param];
    });
}

function registerMorphMesh(scene, morphMesh, folder) {
    const expressions = morphMesh.morphTargetDictionary ? Object.keys(morphMesh.morphTargetDictionary) : [];
    for (let i = 0; i < expressions.length; i++) {
        let ctrl = folder.add(morphMesh.morphTargetInfluences, i, 0, 1, 0.01).name(expressions[i]);
        
        //retreives breathing and blinking morphTarget
        if (expressions[i] == CONFIG.breatheKey) api.breatheCtrl = ctrl;
        if (CONFIG.blinkKeys.includes(expressions[i])) api.blinkCtrls.push(ctrl);

        let subMeshCollection = {};
        scene.traverse(function (obj) {
            if (obj instanceof THREE.Mesh) {
                if (obj.morphTargetDictionary != undefined) {
                    let x = obj.morphTargetDictionary[expressions[i]];
                    if (x != undefined) {
                        subMeshCollection[obj.name] = obj;
                    }
                }
            }
        })
        ctrl.onChange((v) => {
            Object.values(subMeshCollection).forEach((e) => {
                e.morphTargetInfluences[e.morphTargetDictionary[expressions[i]]] = v;
            })
        });
    };
    if (!api.breatheCtrl) console.warn("Breathing animation: MorphTarget for blinking not found.");
    if (api.blinkCtrls.length == 0) console.warn("Breathing animation: MorphTargets for breathing not found.");
}

function addSearch(DOMelementLists) {
    if (DOMelementLists.childNodes.length > 10) {
        let searchBar = document.createElement('input');
        searchBar.type = 'text';
        searchBar.classList.add('search');
        searchBar.placeholder = "Filter by name ...";
        
        searchBar.addEventListener('keyup', () => {
            //skips 1st element as it should be the search input, not a list element
            for (let i = 1; i < DOMelementLists.childNodes.length; i++) {
                if (DOMelementLists.childNodes[i].textContent.toUpperCase().indexOf(searchBar.value.toUpperCase()) > -1) {
                    DOMelementLists.childNodes[i].style.display = '';
                } else {
                    DOMelementLists.childNodes[i].style.display = 'none';
                }
            }
        });
        return searchBar;
    }
    return;
}

function fadeToAction(name, duration) {
    previousAction = activeAction;
    activeAction = actions[name];
    if (previousAction !== activeAction) {
        if(previousAction) previousAction.fadeOut(duration);
    }
    if (activeAction._clip.duration > 0) { //actions are stored directly instead of raw animations, duration is part of the clip child which is the raw animation
        activeAction.loop = THREE.LoopRepeat;
    } else {
        activeAction.loop = THREE.LoopOnce;
    }
    activeAction
        .reset()
        .setEffectiveTimeScale(1)
        .setEffectiveWeight(1)
        .fadeIn(duration)
        .play();
}

function reskinGizmo(gizmo) {
    const colors = {
        x: new THREE.Color(0xe74c3c),
        y: new THREE.Color(0xecc71),
        z: new THREE.Color(0x2980b9),
        xyz: new THREE.Color(0xf1c40f)
    }
    switch (gizmo.mode) {
        case 'translate':
            gizmo._gizmo.gizmo.translate.traverse(child => {
                if (child instanceof THREE.Mesh && (child.name == 'X' || child.name == 'Y' || child.name == 'Z')) {
                    child.geometry = new THREE.CylinderGeometry(0.04, 0.04, 1, 12);
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial);
                    switch (child.name) {
                        case 'X':
                            child.geometry.rotateX(0.5 * Math.PI).rotateY(0.5 * Math.PI);
                            newMat.color = colors.x;
                            break;
                        case 'Y':
                            newMat.color = colors.y;
                            break;
                        case 'Z':
                            child.geometry.rotateX(0.5 * Math.PI).rotateZ(0.5 * Math.PI);
                            newMat.color = colors.z;
                            break;
                    }
                    child.material = newMat;
                } else if (child instanceof THREE.Mesh && child.name == 'XYZ') {
                    child.geometry = new THREE.OctahedronGeometry(0.25, 0);
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial)
                    newMat.color = colors.xyz;
                    child.material = newMat;
                }
            });
            break;
        case 'rotate':
            gizmo._gizmo.gizmo.rotate.traverse(child => {
                if (child instanceof THREE.Mesh && (child.name == 'X' || child.name == 'Y' || child.name ==
                        'Z')) {
                    child.geometry = new THREE.TorusGeometry(0.5, 0.05, 12, 32);
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial);
                    switch (child.name) {
                        case 'X':
                            child.geometry.rotateY(0.5 * Math.PI);
                            newMat.color = colors.x;
                            break;
                        case 'Y':
                            child.geometry.rotateX(0.5 * Math.PI);
                            newMat.color = colors.y;
                            break;
                        case 'Z':
                            newMat.color = colors.z;
                            break;
                    }
                    child.material = newMat;
                } else if (child instanceof THREE.Mesh && child.name == 'E') {
                    child.geometry = new THREE.TorusGeometry(0.7, 0.035, 12, 32);
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial)
                    newMat.color = colors.xyz;
                    child.material = newMat;
                }
            })
            break;
        case 'scale':
            gizmo._gizmo.gizmo.scale.traverse(child => {
                if (child instanceof THREE.Mesh) {
                    let newMat = new THREE.MeshMatcapMaterial({});
                    newMat.copy(MATERIALS.gizmoMaterial);
                    let size = 0.15;
                    switch (child.name) {
                        case 'X':
                            child.geometry = new THREE.BoxGeometry(size, size, size);
                            child.geometry.translate(0.5, 0, 0);
                            newMat.color = colors.x;
                            break;
                        case 'Y':
                            child.geometry = new THREE.BoxGeometry(size, size, size);
                            child.geometry.translate(0, 0.5, 0);
                            newMat.color = colors.y;
                            break;
                        case 'Z':
                            child.geometry = new THREE.BoxGeometry(size, size, size);
                            child.geometry.translate(0, 0, 0.5);
                            newMat.color = colors.z;
                            break;
                        case 'XY':
                            newMat.color = colors.z;
                            break;
                        case 'XZ':
                            newMat.color = colors.y;
                            break;
                        case 'YZ':
                            newMat.color = colors.x;
                            break;
                        case 'XYZ':
                            newMat.color = colors.xyz;
                            break;
                    }
                    child.material = newMat;
                }
            });
            break;
    }
    return gizmo;
}

function gizmoSetup(name, space, mode, size, target) {
    let gizmo = new TransformControls(camera, renderer.domElement);
    gizmo.space = space;
    gizmo.size = size;
    gizmo.setMode(mode);
    reskinGizmo(gizmo);
    gizmoList[name] = false;
    let gizmoHelper = gizmo.getHelper();
    gizmoHelpers[name] = gizmoHelper;
    gizmo.addEventListener('mouseDown', () => controls.enabled = false);
    gizmo.addEventListener('mouseUp', () => controls.enabled = true);

    gizmo.attach(target);

    return gizmo;
}

function applyIK(mesh, name, solver) {
    IKSolvers[name] = new CCDIKSolver(mesh, solver);
    let IKHelper = new CCDIKHelper(mesh, solver, 0.01);
    gizmoList[name + 'Helper'] = false;
    gizmoHelpers[name + 'Helper'] = IKHelper;
    scene.add(IKHelper);

    return IKHelper;
}

function generateUIskeleton(skl, boneCtrlExclusions) {
    for (let i = 0; i < skl.bones.length; i++) {
        if (!boneCtrlExclusions.some(s => skl.bones[i].name.includes(s))) {
            let boneGeometry = new THREE.OctahedronGeometry(0.025, 3)
            let newMat = new THREE.MeshMatcapMaterial({});
            newMat.copy(MATERIALS.gizmoMaterial);
            let boneMesh = new THREE.Mesh(boneGeometry, newMat);
            let target = new THREE.Vector3();
            skl.bones[i].getWorldPosition(target);
            boneMesh.position.set(target.x, target.y, target.z);
            boneMesh.name = skl.bones[i].name;
            bonesGeoList.push(boneMesh);
            scene.add(boneMesh);
        }
    }
}

function getMirrorBoneName(name) {
    let mirrorName = name;
    let side = name.substr(name.length - 1)
    switch (side) {
        case 'L':
            mirrorName = mirrorName.replace(/.$/, 'R');
            break;
        case 'R':
            mirrorName = mirrorName.replace(/.$/, 'L');
            break;
        default:
            return 'none';
    }
    return mirrorName;
}

function setupCustomCtrls(sklHelper, sknMesh) {
    progressState.global = 3 / progressState.total * 100;
    progressState.substep = 0;
    progressState.current = "Setting up IK controls";
    let progress = 0;
    let count = Object.entries(CONFIG.IK).length;

    Object.entries(CONFIG.IK).forEach(e => {
        applyIK(sknMesh, e[0], setupIKchains(sklHelper, e[1]));
        progressState.substep = ++progress / count * 100;
    });
};

function setupIKchains(sklHelper, IKChain) {
    if(IKChain.target && sklHelper.bones.findIndex(o => o.name == IKChain.target) != -1) {
        let computedLinks = [];
        for (let i = 1; i < IKChain.chain.length; i++) {
            computedLinks.push({index: sklHelper.bones.findIndex(o => o.name == IKChain.chain[i])})
        }
        const IKSettings = [{
            target: sklHelper.bones.findIndex(o => o.name == IKChain.target),
            effector: sklHelper.bones.findIndex(o => o.name == IKChain.chain[0]),
            links: computedLinks
        }];
        gizmoSetup(IKChain.target + 'Ctrl', 'world', 'translate', 0.2, sklHelper.bones.find(b => b.name == IKChain.target));
        return IKSettings;
    } else {
        console.warn(IKChain.target + ": Invalid IK setup provided, either bones are absent or settings are incorrect.")
    }
}
